### ISSUE TITLE
Make the Navbar responsive

### ISSUE THREAD

**Issue by shangkaul** [shangkaul/tile-portfolio#4]
- Currently, the navbar does shrink on smaller screens but it's not responsive.
- Make the navbar menu button work so as it opens and closes the navbar **onclick**.
- It'll be amazing if the navbar also closes on clicking anywhere else on the page.
- **Example** - https://adtile.me/fixed-nav/

**Comment by akishtp** [comment]
I would like to work on this.

**Comment by shangkaul** [comment]
> I would like to work on this.

Sure, let me assign this to you
